name: Cloud Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Trigger Cloud Build
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: thejuuma-378904
        service_account_email: 765735516543-compute@developer.gserviceaccount.com
        service_account_key:  {"type": "service_account",
                                "project_id": "thejuuma-378904",
                                "private_key_id": "6a4cf36f7b3a7876410368af5c90e03f4643c4e6",
                                "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDCpKNxnnKka0RY\niUEdLLho/Umvg/JD08hH42I8g5Zh1GKc9fHlF/NNkdtboCV5/3aRoySabdvXZMIZ\n2Dp82yQNsIKHvZxuAj3wopkGd30bKdx/blGFzHpLOUQN5lH6QHDv2O0xAwvy52a7\nXSdRoMu0B6EPYc49Yf43g7tArNok/TuTmiDCdpjcmSXqY/VTrIa4GQeJ5XejaC61\nXJrtGROWUPTKYb1lv2dSoaAc2r1mMpTzqywuxK6S3MggqQqiXh/viROxV2xBA/jv\n4e/i/BucG8FsvQ7DLCkUwDELw/TpGsNHIZKuCndNCNTBs6tqo8zTuNQZ+oZhjt/4\nLx83kLPVAgMBAAECggEAAWmeGU7GSR3igWj7271tj8iP/o2TPLTxvgDAKjXlZWmG\nqCbbYjzLRq7jlZnlDEP1kgs9NK6SQWrE9nJJbfnnfnZF0l6q9E86fTcQmt7kjtsO\n967Il5NW74i4gkQMZBbUVakBervLnC/+Bx74qeUbqRS6wnvVvmqqIDByZtQ0+c/m\nQ+6V2F+nWybhvyTi4C5KjHD1phF13Dbrl69qFmAscBqaEyEPxXIQyqBo02V5aTWw\nmx5HCUpufJuCxUwKfQ83HktHE8UWxeqQ9nO4m4aPPIm1U5JbWJOSK1WqhfHWJd2r\niZQkquxuuRdVUPj61W/gwGRWHChLEdGdojUtGSYw2QKBgQD8eHoDvJxdvJDvFew6\n/WvKWyPXDqbGxXKXFxkIVoQPPvcQERfI2ebJCtBUbR3MwbNXhMOPw3jRM1znwOpT\nL03CqsqNzmTQ8jdIeuagVeZeCmoa21prMALNrW4U1zZE9DFXLlG5F2j73B+IdiaP\nsgGPLJTejsV4jQbKqA+r3JH43QKBgQDFXTaI5FskuNRWNr4+6EeS2wwNauLeSm+X\navurGg+0EtQh2iW40JQfx0PsYuvFzDFB3ESQaAfC8SRVBrQTdn0cigKQaR2JKDQy\nY6imCA58Ts92PnNAmZWgx+PxxH5sSd+muMow+2HBYfi2//A24n6GdVBq3g0J5P3u\ndOzA28t7WQKBgQDoAscOHAwOUDVYoWrfovellC/ReBNnYxe1JXLJqMffQtvElhCn\ncSeW5SsiCsxx2Ce5a7ZTrSygA3WDPFOackQhetZ9jogzRAPtxZOfEJGNJkDvwVjM\nW+iXnqMk38ltgIK/PT+4unytx1HrE7jIIKsyKaP9CnMKH394SQ1twFscuQKBgGSb\nn7Eot02A6r0IKvLmdZXnE73DPuMSDtChOKmAH4EsF/cpvRD5Qojwiy91PbsW3AU2\nw7zZSxuU0XCGekVxoVVrBOOYsfW5COKm6tG4SaoUgq1EKHxFzoCnZQtZnxiUj+3t\nRSSzAKITzzV6Qnm3+8ePBe90QjFJCikEcaveX1wBAoGBAIhdnKZ8MKtY3mNhf5vf\nk73uY6ImcbY4oqR9Xz1LV8h9jToivyQJO/XrjtCYRwo0TFit8Ygorf4Q6jf6Zsts\n3P/WK+ad4vEWe6y1CAt/pi1ml0HvLqzTMQkjUTUd8I6hHcGJ3+oLhltqRNbulIPB\nnu73jMxlKZFDv+Un/5oqOQa6\n-----END PRIVATE KEY-----\n",
                                "client_email": "765735516543-compute@developer.gserviceaccount.com",
                                "client_id": "113210585372984071958",
                                "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                                "token_uri": "https://oauth2.googleapis.com/token",
                                "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
                                "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/765735516543-compute%40developer.gserviceaccount.com"}

    - run: |
        gcloud builds submit --config cloudbuild.yaml .
        export BUILD_ID="$(gcloud builds list --limit=1 --format='get(id)')"
        gcloud builds log "$BUILD_ID"
      continue-on-error: true

    - name: Display Cloud Build Logs
      uses: google-github-actions/cloud-build-logs@master
      with:
        build_id: ${{ env.BUILD_ID }}
